CREATE DATABASE BD_ACTIVIDAD4

USE BD_ACTIVIDAD4

CREATE TABLE CARRERAS

(
ID_CARRERA INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_CARRERA NVARCHAR (100)
);

CREATE TABLE MATERIAS 
(
CODIGO_MATERIA NVARCHAR (20) PRIMARY KEY,
NOMBRE_MATERIA NVARCHAR (100) NOT NULL, 
CREDITOS INT NOT NULL CHECK (CREDITOS BETWEEN 1 AND 4),
ID_CARRERA INT NOT NULL FOREIGN KEY REFERENCES CARRERAS (ID_CARRERA), 
);

CREATE TABLE ESTUDIANTES 
(
ID_ESTUDIANTE INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_COMPLETO NVARCHAR (100) NOT NULL,
MATRICULA NVARCHAR (15) NOT NULL UNIQUE CHECK (LEN(MATRICULA) >=6),
ID_CARRERA INT NOT NULL FOREIGN KEY REFERENCES CARRERAS (ID_CARRERA), 
CORREO_INSTITUCIONAL NVARCHAR (255) NOT NULL CHECK (CORREO_INSTITUCIONAL LIKE '%@%.%'),
TELEFONO BIGINT NOT NULL, 
FECHA_NAC DATE NOT NULL, 
GENERO NVARCHAR (10) NOT NULL CHECK (GENERO IN ('MASCULINO', 'FEMENINO')),
TURNO NVARCHAR (10) NOT NULL CHECK (TURNO IN ('MATUTINO', 'VESPERTINO', 'NOCTURNO')),
TIPO_INGRESO NVARCHAR (50) NOT NULL CHECK (TIPO_INGRESO IN ('NUEVO_INGRESO', 'REINGRESO', 'INGRESO_TRANSFERENCIA', 'DOCTORADO')), 
ESTA_BECADO BIT NOT NULL, 
PORCENTAJE_BECA INT NULL CHECK (PORCENTAJE_BECA BETWEEN 0 AND 100),
TERMINOS_CONDICIONES BIT NOT NULL CHECK (TERMINOS_CONDICIONES = 1),
);

CREATE TABLE CALIFICACIONES 
(
ID_CALIFICACIONES INT PRIMARY KEY IDENTITY (1,1),
MATRICULA_ESTUDIANTE NVARCHAR (15) NOT NULL FOREIGN KEY REFERENCES ESTUDIANTES (MATRICULA), 
CODIGO_MATERIA NVARCHAR (20) NOT NULL FOREIGN KEY REFERENCES MATERIAS (CODIGO_MATERIA),
NOTA DECIMAL (5,2) NOT NULL CHECK (NOTA BETWEEN 0 AND 100),
PERIODO NVARCHAR (20) NOT NULL,
);

